services:
  todo-list:
    image: todo-list:0.0.1
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - todo-list-network
    volumes:
      - ./application.yml:/app/src/main/resources/application.yml
      - ./.env:/app/.env
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: mysqldb
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - todo-list-network
volumes:
    mysql-data:

networks:
  todo-list-network:
    name: todo-list-network