services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.9.3
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka-broker-1:
    container_name: kafka-broker-1
    image: bitnami/kafka:3.7.1
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-1:29092,EXTERNAL://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#      KAFKA_CFG_ZOOKEEPER_SESSION_TIMEOUT: "6000"
#      KAFKA_CFG_RESTART_ATTEMPTS: "10"
#      KAFKA_CFG_RESTART_DELAY: "5"
#      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  kafka-broker-2:
    container_name: kafka-broker-2
    image: bitnami/kafka:3.7.1
    restart: always
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "INTERNAL://:29093,EXTERNAL://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-2:29093,EXTERNAL://localhost:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  kafka-broker-3:
    container_name: kafka-broker-3
    image: bitnami/kafka:3.7.1
    restart: always
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "INTERNAL://:29094,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker-3:29094,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  mysqldb:
    image: mysql:8.0.33
    container_name: mysqldb
    ports:
      - "3307:3306"
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql

  kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-broker-1:29092,kafka-broker-2:29093,kafka-broker-3:29094"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_PORT: 9000
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

  redis:
    image: redis:8.0.1
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: .env
#    volumes:
#      - redis-data:/data

#volumes:
#  redis-data: