spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"
    consumer:
      group-id: "notification-group"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
            spring.json.add.type.headers: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 6000ms
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10s

logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.kafka.org.springframework.kafka.listener: DEBUG
    org.apache.kafka.clients.consumer: INFO
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE